policies:
  - name: "KerasPolicy"
  - name: "MemoizationPolicy"
    max_history: 3
  - name: "TwoStageFallbackPolicy"
    nlu_threshold: 0.8
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"
